coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
			  only_pulls: false
        branches: null
        flags: null
				paths: null
